coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
			  only_pulls: false
        branches: null
        flags: null
				paths: null
